type Track {
  name: String!
  description: String
  userEmail: String!
  public: Boolean!
  links: [Link] @relation
}

type Link {
  title: String!
  url: String!
  track: Track
}

type Query {
  tracks: [Track!]
  tracksByPublicFlag(public: Boolean!): [Track!]
  tracksByUserEmail(userEmail: String!): [Track!]
  trackList(userEmail: String): [Track!] @resolver(name: "track_list", paginated: true)
}

type Mutation {
  trackCascadeDelete(id: ID!): Track! @resolver(name: "track_cascade_delete")
}